/**
 * DAILY TOP 10 — curated challenge bank. SERVER ONLY.
 *
 * This file never reaches the browser (`*.server.ts` is blocked from client
 * bundles), which is the whole point: the answers must not ship in the page
 * payload. The client only ever receives a prompt, and one answer at a time
 * as it is correctly guessed — or the full list after an explicit give-up.
 *
 * DATA POLICY
 * - Every list is factual and orderable from a public, checkable source.
 *   Box-office rankings are worldwide theatrical grosses as reported by
 *   Box Office Mojo / The Numbers; award lists are the Academy's own record.
 * - No subjective "best of" rankings, and no IMDb ratings — deliberately.
 * - Where a ranking is sensitive to re-releases or a cut-off date, the
 *   subtitle says so rather than pretending the order is eternal.
 */

import type { Top10AnswerType } from "./types";

export interface Top10Challenge {
  /** Stable id — also the calendar key. Never renumber. */
  id: string;
  title: string;
  subtitle?: string;
  category: "box-office" | "awards" | "franchise";
  /** What the ten blanks hold. Defaults to "film". Drives autocomplete only. */
  answerType?: Top10AnswerType;
  source: string;
  sourceUrl?: string;
  published: boolean;
  /** Exactly ten, in true ranked order (position 1 first). */
  answers: string[];
}

const BOM = "Box Office Mojo — worldwide grosses";
const BOM_URL = "https://www.boxofficemojo.com/";
const OSCARS = "Academy of Motion Picture Arts and Sciences — official winners";
const OSCARS_URL = "https://www.oscars.org/oscars/ceremonies";

/** Highest-grossing films worldwide for a single release year. */
function year(y: number, answers: string[]): Top10Challenge {
  return {
    id: `wwbo-${y}`,
    title: `Highest-grossing films worldwide of ${y}`,
    subtitle: "Ranked by worldwide theatrical gross for that release year.",
    category: "box-office",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers,
  };
}

export const CHALLENGES: Top10Challenge[] = [
  year(2001, [
    "Harry Potter and the Philosopher's Stone",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Monsters, Inc.",
    "Shrek",
    "Ocean's Eleven",
    "Pearl Harbor",
    "Jurassic Park III",
    "The Mummy Returns",
    "Planet of the Apes",
    "Hannibal",
  ]),
  year(2002, [
    "The Lord of the Rings: The Two Towers",
    "Harry Potter and the Chamber of Secrets",
    "Spider-Man",
    "Star Wars: Episode II – Attack of the Clones",
    "Men in Black II",
    "Die Another Day",
    "Signs",
    "Ice Age",
    "My Big Fat Greek Wedding",
    "Minority Report",
  ]),
  year(2003, [
    "The Lord of the Rings: The Return of the King",
    "Finding Nemo",
    "The Matrix Reloaded",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Bruce Almighty",
    "The Last Samurai",
    "Terminator 3: Rise of the Machines",
    "The Matrix Revolutions",
    "X2: X-Men United",
    "Bad Boys II",
  ]),
  year(2004, [
    "Shrek 2",
    "Harry Potter and the Prisoner of Azkaban",
    "Spider-Man 2",
    "The Incredibles",
    "The Passion of the Christ",
    "The Day After Tomorrow",
    "Meet the Fockers",
    "Troy",
    "Shark Tale",
    "Ocean's Twelve",
  ]),
  year(2005, [
    "Harry Potter and the Goblet of Fire",
    "Star Wars: Episode III – Revenge of the Sith",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "War of the Worlds",
    "King Kong",
    "Madagascar",
    "Mr. & Mrs. Smith",
    "Charlie and the Chocolate Factory",
    "Batman Begins",
    "Hitch",
  ]),
  year(2006, [
    "Pirates of the Caribbean: Dead Man's Chest",
    "The Da Vinci Code",
    "Ice Age: The Meltdown",
    "Casino Royale",
    "Night at the Museum",
    "Cars",
    "X-Men: The Last Stand",
    "Mission: Impossible III",
    "Superman Returns",
    "Happy Feet",
  ]),
  year(2007, [
    "Pirates of the Caribbean: At World's End",
    "Harry Potter and the Order of the Phoenix",
    "Spider-Man 3",
    "Shrek the Third",
    "Transformers",
    "Ratatouille",
    "I Am Legend",
    "The Simpsons Movie",
    "National Treasure: Book of Secrets",
    "300",
  ]),
  year(2008, [
    "The Dark Knight",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "Kung Fu Panda",
    "Hancock",
    "Mamma Mia!",
    "Madagascar: Escape 2 Africa",
    "Quantum of Solace",
    "Iron Man",
    "WALL-E",
    "The Chronicles of Narnia: Prince Caspian",
  ]),
  year(2009, [
    "Avatar",
    "Harry Potter and the Half-Blood Prince",
    "Ice Age: Dawn of the Dinosaurs",
    "Transformers: Revenge of the Fallen",
    "2012",
    "Up",
    "The Twilight Saga: New Moon",
    "Sherlock Holmes",
    "Angels & Demons",
    "The Hangover",
  ]),
  year(2010, [
    "Toy Story 3",
    "Alice in Wonderland",
    "Harry Potter and the Deathly Hallows – Part 1",
    "Inception",
    "Shrek Forever After",
    "The Twilight Saga: Eclipse",
    "Iron Man 2",
    "Tangled",
    "Despicable Me",
    "How to Train Your Dragon",
  ]),
  year(2011, [
    "Harry Potter and the Deathly Hallows – Part 2",
    "Transformers: Dark of the Moon",
    "Pirates of the Caribbean: On Stranger Tides",
    "The Twilight Saga: Breaking Dawn – Part 1",
    "Mission: Impossible – Ghost Protocol",
    "Kung Fu Panda 2",
    "Fast Five",
    "The Hangover Part II",
    "The Smurfs",
    "Cars 2",
  ]),
  year(2012, [
    "The Avengers",
    "Skyfall",
    "The Dark Knight Rises",
    "The Hobbit: An Unexpected Journey",
    "Ice Age: Continental Drift",
    "The Twilight Saga: Breaking Dawn – Part 2",
    "The Amazing Spider-Man",
    "Madagascar 3: Europe's Most Wanted",
    "The Hunger Games",
    "Men in Black 3",
  ]),
  year(2013, [
    "Frozen",
    "Iron Man 3",
    "Despicable Me 2",
    "The Hobbit: The Desolation of Smaug",
    "The Hunger Games: Catching Fire",
    "Fast & Furious 6",
    "Monsters University",
    "Gravity",
    "Man of Steel",
    "Thor: The Dark World",
  ]),
  year(2014, [
    "Transformers: Age of Extinction",
    "The Hobbit: The Battle of the Five Armies",
    "Guardians of the Galaxy",
    "Maleficent",
    "The Hunger Games: Mockingjay – Part 1",
    "X-Men: Days of Future Past",
    "Captain America: The Winter Soldier",
    "Dawn of the Planet of the Apes",
    "The Amazing Spider-Man 2",
    "Interstellar",
  ]),
  year(2015, [
    "Star Wars: The Force Awakens",
    "Jurassic World",
    "Furious 7",
    "Avengers: Age of Ultron",
    "Minions",
    "Spectre",
    "Inside Out",
    "Mission: Impossible – Rogue Nation",
    "The Martian",
    "Fifty Shades of Grey",
  ]),
  year(2016, [
    "Captain America: Civil War",
    "Rogue One: A Star Wars Story",
    "Finding Dory",
    "Zootopia",
    "The Jungle Book",
    "The Secret Life of Pets",
    "Batman v Superman: Dawn of Justice",
    "Fantastic Beasts and Where to Find Them",
    "Deadpool",
    "Suicide Squad",
  ]),
  year(2017, [
    "Star Wars: The Last Jedi",
    "Beauty and the Beast",
    "The Fate of the Furious",
    "Despicable Me 3",
    "Jumanji: Welcome to the Jungle",
    "Spider-Man: Homecoming",
    "Wolf Warrior 2",
    "Guardians of the Galaxy Vol. 2",
    "Thor: Ragnarok",
    "Wonder Woman",
  ]),
  year(2018, [
    "Avengers: Infinity War",
    "Black Panther",
    "Jurassic World: Fallen Kingdom",
    "Incredibles 2",
    "Aquaman",
    "Bohemian Rhapsody",
    "Venom",
    "Mission: Impossible – Fallout",
    "Deadpool 2",
    "Fantastic Beasts: The Crimes of Grindelwald",
  ]),
  year(2019, [
    "Avengers: Endgame",
    "The Lion King",
    "Frozen II",
    "Spider-Man: Far From Home",
    "Captain Marvel",
    "Joker",
    "Star Wars: The Rise of Skywalker",
    "Toy Story 4",
    "Aladdin",
    "Fast & Furious Presents: Hobbs & Shaw",
  ]),
  year(2023, [
    "Barbie",
    "The Super Mario Bros. Movie",
    "Oppenheimer",
    "Guardians of the Galaxy Vol. 3",
    "Fast X",
    "Spider-Man: Across the Spider-Verse",
    "The Little Mermaid",
    "Mission: Impossible – Dead Reckoning Part One",
    "Wonka",
    "Elemental",
  ]),
  year(2024, [
    "Inside Out 2",
    "Deadpool & Wolverine",
    "Moana 2",
    "Despicable Me 4",
    "Wicked",
    "Dune: Part Two",
    "Godzilla x Kong: The New Empire",
    "Kung Fu Panda 4",
    "Sonic the Hedgehog 3",
    "Venom: The Last Dance",
  ]),
  {
    id: "wwbo-alltime",
    title: "Highest-grossing films of all time, worldwide",
    subtitle: "Cumulative worldwide gross including re-releases, through the 2024 box-office year.",
    category: "box-office",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers: [
      "Avatar",
      "Avengers: Endgame",
      "Avatar: The Way of Water",
      "Titanic",
      "Star Wars: The Force Awakens",
      "Avengers: Infinity War",
      "Spider-Man: No Way Home",
      "Inside Out 2",
      "Jurassic World",
      "The Lion King",
    ],
  },
  {
    id: "wwbo-1990s",
    title: "Highest-grossing films of the 1990s, worldwide",
    subtitle: "Ranked by worldwide gross for films released 1990–1999.",
    category: "box-office",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers: [
      "Titanic",
      "Star Wars: Episode I – The Phantom Menace",
      "Jurassic Park",
      "Independence Day",
      "The Lion King",
      "Forrest Gump",
      "The Sixth Sense",
      "The Lost World: Jurassic Park",
      "Men in Black",
      "Armageddon",
    ],
  },
  {
    id: "wwbo-1980s",
    title: "Highest-grossing films of the 1980s, worldwide",
    subtitle: "Ranked by worldwide gross for films released 1980–1989, original releases.",
    category: "box-office",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers: [
      "E.T. the Extra-Terrestrial",
      "Return of the Jedi",
      "The Empire Strikes Back",
      "Indiana Jones and the Last Crusade",
      "Batman",
      "Rain Man",
      "Back to the Future",
      "Raiders of the Lost Ark",
      "Top Gun",
      "Who Framed Roger Rabbit",
    ],
  },
  {
    id: "franchise-pixar",
    title: "Highest-grossing Pixar films, worldwide",
    subtitle: "Feature films produced by Pixar Animation Studios, by worldwide gross.",
    category: "franchise",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers: [
      "Inside Out 2",
      "Incredibles 2",
      "Toy Story 4",
      "Toy Story 3",
      "Finding Dory",
      "Finding Nemo",
      "Inside Out",
      "Coco",
      "Monsters University",
      "Up",
    ],
  },
  {
    id: "franchise-mcu",
    title: "Highest-grossing Marvel Cinematic Universe films",
    subtitle: "Worldwide gross, films released under the MCU banner.",
    category: "franchise",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers: [
      "Avengers: Endgame",
      "Avengers: Infinity War",
      "Spider-Man: No Way Home",
      "The Avengers",
      "Avengers: Age of Ultron",
      "Black Panther",
      "Deadpool & Wolverine",
      "Iron Man 3",
      "Captain America: Civil War",
      "Captain Marvel",
    ],
  },
  {
    id: "franchise-potter",
    title: "Highest-grossing Wizarding World films",
    subtitle: "Harry Potter and Fantastic Beasts films, by worldwide gross.",
    category: "franchise",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers: [
      "Harry Potter and the Deathly Hallows – Part 2",
      "Harry Potter and the Philosopher's Stone",
      "Harry Potter and the Deathly Hallows – Part 1",
      "Harry Potter and the Order of the Phoenix",
      "Harry Potter and the Half-Blood Prince",
      "Harry Potter and the Goblet of Fire",
      "Harry Potter and the Chamber of Secrets",
      "Fantastic Beasts and Where to Find Them",
      "Harry Potter and the Prisoner of Azkaban",
      "Fantastic Beasts: The Crimes of Grindelwald",
    ],
  },
  {
    id: "franchise-bond",
    title: "Highest-grossing James Bond films",
    subtitle: "Worldwide gross, unadjusted for inflation.",
    category: "franchise",
    source: BOM,
    sourceUrl: BOM_URL,
    published: true,
    answers: [
      "Skyfall",
      "Spectre",
      "No Time to Die",
      "Casino Royale",
      "Quantum of Solace",
      "Die Another Day",
      "The World Is Not Enough",
      "GoldenEye",
      "Tomorrow Never Dies",
      "Moonraker",
    ],
  },
  {
    id: "oscars-bp-2015-2024",
    title: "Best Picture winners, ceremonies 2015–2024",
    subtitle: "In chronological order — position 1 is the 2015 ceremony.",
    category: "awards",
    source: OSCARS,
    sourceUrl: OSCARS_URL,
    published: true,
    answers: [
      "Birdman",
      "Spotlight",
      "Moonlight",
      "The Shape of Water",
      "Green Book",
      "Parasite",
      "Nomadland",
      "CODA",
      "Everything Everywhere All at Once",
      "Oppenheimer",
    ],
  },
  {
    id: "oscars-bp-2005-2014",
    title: "Best Picture winners, ceremonies 2005–2014",
    subtitle: "In chronological order — position 1 is the 2005 ceremony.",
    category: "awards",
    source: OSCARS,
    sourceUrl: OSCARS_URL,
    published: true,
    answers: [
      "Million Dollar Baby",
      "Crash",
      "The Departed",
      "No Country for Old Men",
      "Slumdog Millionaire",
      "The Hurt Locker",
      "The King's Speech",
      "The Artist",
      "Argo",
      "12 Years a Slave",
    ],
  },
  {
    id: "oscars-bp-1995-2004",
    title: "Best Picture winners, ceremonies 1995–2004",
    subtitle: "In chronological order — position 1 is the 1995 ceremony.",
    category: "awards",
    source: OSCARS,
    sourceUrl: OSCARS_URL,
    published: true,
    answers: [
      "Forrest Gump",
      "Braveheart",
      "The English Patient",
      "Titanic",
      "Shakespeare in Love",
      "American Beauty",
      "Gladiator",
      "A Beautiful Mind",
      "Chicago",
      "The Lord of the Rings: The Return of the King",
    ],
  },
  {
    id: "oscars-bp-1985-1994",
    title: "Best Picture winners, ceremonies 1985–1994",
    subtitle: "In chronological order — position 1 is the 1985 ceremony.",
    category: "awards",
    source: OSCARS,
    sourceUrl: OSCARS_URL,
    published: true,
    answers: [
      "Amadeus",
      "Out of Africa",
      "Platoon",
      "The Last Emperor",
      "Rain Man",
      "Driving Miss Daisy",
      "Dances with Wolves",
      "The Silence of the Lambs",
      "Unforgiven",
      "Schindler's List",
    ],
  },
  {
    id: "oscars-actor-2015-2024",
    answerType: "person",
    title: "Best Actor winners, ceremonies 2015–2024",
    subtitle: "In chronological order — position 1 is the 2015 ceremony.",
    category: "awards",
    source: OSCARS,
    sourceUrl: OSCARS_URL,
    published: true,
    answers: [
      "Eddie Redmayne",
      "Leonardo DiCaprio",
      "Casey Affleck",
      "Gary Oldman",
      "Rami Malek",
      "Joaquin Phoenix",
      "Anthony Hopkins",
      "Will Smith",
      "Brendan Fraser",
      "Cillian Murphy",
    ],
  },
];

/**
 * Extra accepted spellings, keyed by canonical answer. Normalisation already
 * handles case, accents, punctuation, "&"/"and" and a leading "the", so this
 * only carries the shorthand people actually type.
 */
export const ALIASES: Record<string, string[]> = {
  "Avengers: Endgame": ["endgame"],
  "Avengers: Infinity War": ["infinity war"],
  "Avengers: Age of Ultron": ["age of ultron"],
  "The Avengers": ["avengers", "avengers assemble"],
  "Spider-Man: No Way Home": ["no way home"],
  "Spider-Man: Far From Home": ["far from home"],
  "Spider-Man: Homecoming": ["homecoming"],
  "Spider-Man: Across the Spider-Verse": ["across the spider verse", "spider verse 2"],
  "Harry Potter and the Philosopher's Stone": [
    "harry potter and the sorcerers stone",
    "harry potter 1",
    "philosophers stone",
    "sorcerers stone",
  ],
  "Harry Potter and the Chamber of Secrets": ["harry potter 2", "chamber of secrets"],
  "Harry Potter and the Prisoner of Azkaban": ["harry potter 3", "prisoner of azkaban"],
  "Harry Potter and the Goblet of Fire": ["harry potter 4", "goblet of fire"],
  "Harry Potter and the Order of the Phoenix": ["harry potter 5", "order of the phoenix"],
  "Harry Potter and the Half-Blood Prince": ["harry potter 6", "half blood prince"],
  "Harry Potter and the Deathly Hallows – Part 1": [
    "harry potter and the deathly hallows part 1",
    "harry potter 7",
    "deathly hallows part 1",
    "deathly hallows 1",
  ],
  "Harry Potter and the Deathly Hallows – Part 2": [
    "harry potter and the deathly hallows part 2",
    "harry potter 8",
    "deathly hallows part 2",
    "deathly hallows 2",
  ],
  "Fantastic Beasts and Where to Find Them": ["fantastic beasts"],
  "Fantastic Beasts: The Crimes of Grindelwald": ["crimes of grindelwald", "fantastic beasts 2"],
  "The Lord of the Rings: The Fellowship of the Ring": [
    "fellowship of the ring",
    "lotr fellowship of the ring",
    "lotr 1",
  ],
  "The Lord of the Rings: The Two Towers": ["two towers", "lotr two towers", "lotr 2"],
  "The Lord of the Rings: The Return of the King": [
    "return of the king",
    "lotr return of the king",
    "lotr 3",
  ],
  "Star Wars: Episode I – The Phantom Menace": [
    "star wars episode 1 the phantom menace",
    "the phantom menace",
    "star wars episode i",
  ],
  "Star Wars: Episode II – Attack of the Clones": [
    "star wars episode 2 attack of the clones",
    "attack of the clones",
    "star wars episode ii",
  ],
  "Star Wars: Episode III – Revenge of the Sith": [
    "star wars episode 3 revenge of the sith",
    "revenge of the sith",
    "star wars episode iii",
  ],
  "Star Wars: The Force Awakens": ["force awakens", "star wars episode 7"],
  "Star Wars: The Last Jedi": ["last jedi", "star wars episode 8"],
  "Star Wars: The Rise of Skywalker": ["rise of skywalker", "star wars episode 9"],
  "Return of the Jedi": ["star wars return of the jedi", "star wars episode 6"],
  "The Empire Strikes Back": ["star wars the empire strikes back", "star wars episode 5"],
  "Rogue One: A Star Wars Story": ["rogue one"],
  "E.T. the Extra-Terrestrial": ["et", "et the extra terrestrial"],
  "WALL-E": ["wall e", "walle"],
  "Mission: Impossible III": ["mission impossible 3", "mi3"],
  "Mission: Impossible – Ghost Protocol": ["mission impossible ghost protocol", "ghost protocol"],
  "Mission: Impossible – Rogue Nation": ["mission impossible rogue nation", "rogue nation"],
  "Mission: Impossible – Fallout": ["mission impossible fallout", "fallout"],
  "Mission: Impossible – Dead Reckoning Part One": [
    "mission impossible dead reckoning part one",
    "mission impossible dead reckoning",
    "dead reckoning",
  ],
  "The Hunger Games: Mockingjay – Part 1": [
    "the hunger games mockingjay part 1",
    "mockingjay part 1",
    "mockingjay",
  ],
  "The Hunger Games: Catching Fire": ["catching fire"],
  "The Twilight Saga: Breaking Dawn – Part 1": [
    "the twilight saga breaking dawn part 1",
    "breaking dawn part 1",
    "breaking dawn 1",
  ],
  "The Twilight Saga: Breaking Dawn – Part 2": [
    "the twilight saga breaking dawn part 2",
    "breaking dawn part 2",
    "breaking dawn 2",
  ],
  "The Twilight Saga: New Moon": ["new moon", "twilight new moon"],
  "The Twilight Saga: Eclipse": ["eclipse", "twilight eclipse"],
  "Pirates of the Caribbean: The Curse of the Black Pearl": [
    "curse of the black pearl",
    "pirates of the caribbean",
    "pirates of the caribbean 1",
  ],
  "Pirates of the Caribbean: Dead Man's Chest": ["dead mans chest", "pirates of the caribbean 2"],
  "Pirates of the Caribbean: At World's End": ["at worlds end", "pirates of the caribbean 3"],
  "Pirates of the Caribbean: On Stranger Tides": [
    "on stranger tides",
    "pirates of the caribbean 4",
  ],
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe": [
    "narnia",
    "the lion the witch and the wardrobe",
    "narnia the lion the witch and the wardrobe",
  ],
  "The Chronicles of Narnia: Prince Caspian": ["prince caspian", "narnia prince caspian"],
  "Madagascar 3: Europe's Most Wanted": ["madagascar 3"],
  "Madagascar: Escape 2 Africa": ["madagascar 2", "madagascar escape 2 africa"],
  "Ice Age: Dawn of the Dinosaurs": ["ice age 3", "dawn of the dinosaurs"],
  "Ice Age: The Meltdown": ["ice age 2", "the meltdown"],
  "Ice Age: Continental Drift": ["ice age 4", "continental drift"],
  "The Hobbit: An Unexpected Journey": ["an unexpected journey", "the hobbit 1"],
  "The Hobbit: The Desolation of Smaug": ["desolation of smaug", "the hobbit 2"],
  "The Hobbit: The Battle of the Five Armies": ["battle of the five armies", "the hobbit 3"],
  "X2: X-Men United": ["x2", "x men united", "x men 2"],
  "X-Men: Days of Future Past": ["days of future past"],
  "X-Men: The Last Stand": ["x men 3", "the last stand"],
  "Captain America: The Winter Soldier": ["the winter soldier", "captain america 2"],
  "Captain America: Civil War": ["civil war", "captain america 3"],
  "Guardians of the Galaxy Vol. 2": ["guardians of the galaxy 2", "guardians of the galaxy vol 2"],
  "Guardians of the Galaxy Vol. 3": ["guardians of the galaxy 3", "guardians of the galaxy vol 3"],
  "Thor: Ragnarok": ["ragnarok"],
  "Thor: The Dark World": ["the dark world", "thor 2"],
  "Batman v Superman: Dawn of Justice": ["batman v superman", "batman vs superman"],
  "Fast & Furious Presents: Hobbs & Shaw": ["hobbs and shaw", "hobbs shaw"],
  "Fast & Furious 6": ["fast 6", "furious 6"],
  "The Fate of the Furious": ["fast 8", "fate of the furious"],
  "Furious 7": ["fast 7", "fast and furious 7"],
  "Fast Five": ["fast 5", "fast and furious 5"],
  "Fast X": ["fast 10"],
  "Godzilla x Kong: The New Empire": ["godzilla x kong", "the new empire"],
  "Transformers: Revenge of the Fallen": ["transformers 2", "revenge of the fallen"],
  "Transformers: Dark of the Moon": ["transformers 3", "dark of the moon"],
  "Transformers: Age of Extinction": ["transformers 4", "age of extinction"],
  "Indiana Jones and the Kingdom of the Crystal Skull": ["kingdom of the crystal skull", "indiana jones 4"],
  "Indiana Jones and the Last Crusade": ["the last crusade", "indiana jones 3"],
  "Raiders of the Lost Ark": ["indiana jones raiders of the lost ark", "indiana jones 1"],
  "National Treasure: Book of Secrets": ["book of secrets", "national treasure 2"],
  "Jumanji: Welcome to the Jungle": ["welcome to the jungle"],
  "Dawn of the Planet of the Apes": ["dawn of the apes"],
  "The Lost World: Jurassic Park": ["the lost world", "jurassic park 2"],
  "Jurassic World: Fallen Kingdom": ["fallen kingdom", "jurassic world 2"],
  "Jurassic Park III": ["jurassic park 3"],
  "Dune: Part Two": ["dune part 2", "dune 2"],
  "Terminator 3: Rise of the Machines": ["terminator 3", "rise of the machines"],
  "Venom: The Last Dance": ["the last dance", "venom 3"],
  "Avatar: The Way of Water": ["the way of water", "avatar 2"],
  "Monsters, Inc.": ["monsters inc"],
  "The Super Mario Bros. Movie": ["super mario bros movie", "mario movie", "the super mario bros movie"],
  "Birdman": ["birdman or the unexpected virtue of ignorance"],
  "12 Years a Slave": ["twelve years a slave"],
  "Angels & Demons": ["angels and demons"],
  "Mr. & Mrs. Smith": ["mr and mrs smith", "mr mrs smith"],
  "Fifty Shades of Grey": ["50 shades of grey"],
  "The Hangover Part II": ["the hangover 2", "the hangover part 2"],
  "Men in Black II": ["men in black 2", "mib 2"],
  "Men in Black 3": ["mib 3"],
  "Men in Black": ["mib"],
  "Bad Boys II": ["bad boys 2"],
  "Kung Fu Panda 4": ["kung fu panda four"],
  "The Matrix Reloaded": ["matrix 2"],
  "The Matrix Revolutions": ["matrix 3"],
};
