/**
 * CONNECT — client snapshot generator.
 *
 * Supabase is the authoritative catalogue; this emits the playable client
 * representation FROM it, so the database and the board can no longer drift.
 * The output is content-hashed and the hash is written into
 * `src/games/connect/data/version.ts`, which the loader appends to the fetch
 * URL — a catalogue deploy therefore always busts returning users' caches.
 *
 *   bun scripts/connect/build-graph.ts
 */

import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env["SUPABASE_URL"]!,
  process.env["SUPABASE_SERVICE_ROLE_KEY"]!,
  { auth: { persistSession: false } },
);

const PAGE = 1000;

async function all<T>(table: string, columns: string, order: string): Promise<T[]> {
  const rows: T[] = [];
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await supabase
      .from(table)
      .select(columns)
      .order(order)
      .range(from, from + PAGE - 1);
    if (error) throw new Error(`${table}: ${error.message}`);
    rows.push(...((data ?? []) as unknown as T[]));
    if (!data || data.length < PAGE) break;
    if (from % 50000 === 0) console.log(`${table}: ${rows.length}`);
  }
  return rows;
}

interface DbPerson {
  id: string;
  name: string;
  notability: number;
  birth_year: number | null;
  image_file: string | null;
  coverage_status: string;
}
interface DbMovie { id: string; title: string; year: number; notability: number }
interface DbCast { movie_id: string; person_id: string; billing: number | null; character_name: string | null }

const people = await all<DbPerson>("connect_people", "id, name, notability, birth_year, image_file, coverage_status", "id");
const movies = await all<DbMovie>("connect_movies", "id, title, year, notability", "id");
const cast = await all<DbCast>("connect_cast", "movie_id, person_id, billing, character_name", "movie_id");
console.log(`db: ${people.length} people, ${movies.length} films, ${cast.length} credits`);

// Keep only people who can actually be traversed: playables always, plus any
// connector with at least two credits (a single-credit connector is a
// dead-end node that costs payload and can never complete a path).
const credits = new Map<string, number>();
for (const c of cast) credits.set(c.person_id, (credits.get(c.person_id) ?? 0) + 1);

const keptPeople = people.filter(
  (p) => p.coverage_status === "playable" || (credits.get(p.id) ?? 0) >= 2,
);
const personIndex = new Map(keptPeople.map((p, i) => [p.id, i]));

const movieIndex = new Map(movies.map((m, i) => [m.id, i]));
const castByMovie: [number, number, string][][] = movies.map(() => []);
for (const c of cast) {
  const mi = movieIndex.get(c.movie_id);
  const pi = personIndex.get(c.person_id);
  if (mi === undefined || pi === undefined) continue;
  castByMovie[mi]!.push([pi, c.billing ?? 0, c.character_name ?? ""]);
}
for (const row of castByMovie) row.sort((a, b) => (a[1] || 999) - (b[1] || 999));

const dataset = {
  version: "",
  source: "Wikidata (CC0) + Wikimedia Commons image metadata — coverage-tiered ingestion",
  generated: new Date().toISOString(),
  people: keptPeople.map((p) => [
    p.id,
    p.name,
    p.notability,
    p.image_file ?? "",
    p.birth_year ?? 0,
    p.coverage_status === "playable" ? 1 : 0,
  ]),
  films: movies.map((m) => [m.id, m.title, m.year, m.notability]),
  cast: castByMovie,
};

const body = JSON.stringify(dataset);
const version = createHash("sha256").update(body).digest("hex").slice(0, 12);
dataset.version = version;
const out = JSON.stringify(dataset);

writeFileSync("public/data/connect-graph.json", out);
writeFileSync(
  "src/games/connect/data/version.ts",
  `/** Generated by scripts/connect/build-graph.ts — do not edit by hand. */\nexport const GRAPH_VERSION = "${version}";\n`,
);

const playable = keptPeople.filter((p) => p.coverage_status === "playable").length;
console.log({
  version,
  playable,
  connectors: keptPeople.length - playable,
  films: movies.length,
  edges: castByMovie.reduce((n, r) => n + r.length, 0),
  rawMB: +(out.length / 1e6).toFixed(2),
  gzipMB: +(gzipSync(out).length / 1e6).toFixed(2),
});
