import { GRAPH } from "../src/games/connect/graph";
const ppl = Object.values(GRAPH.peopleById);
console.log("people", ppl.length, "movies", GRAPH.movieIds.length);
const withN = (n:number)=>ppl.filter(p=>p.movieIds.length>=n).length;
for (const n of [2,3,4,5,6,8,10,15]) console.log("credits>=",n, withN(n));
const modern = ppl.filter(p=>p.movieIds.some(id=>GRAPH.moviesById[id]!.year>=1995));
console.log("any credit >=1995", modern.length);
const pool = ppl.filter(p=>p.movieIds.length>=5 && p.movieIds.some(id=>GRAPH.moviesById[id]!.year>=1995));
console.log("pool 5+ & modern", pool.length);
console.log(pool.slice(0,40).map(p=>p.name).join(", "));
