/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HigherLowerRouteImport } from './routes/higher-lower'
import { Route as HollywoodRouteImport } from './routes/hollywood'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalkOfFameRouteImport } from './routes/walk-of-fame'
import { Route as ApiPublicConnectImportRouteImport } from './routes/api/public/connect-import'
import { Route as ApiPublicDailyConnectPublishRouteImport } from './routes/api/public/daily-connect-publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HigherLowerRoute = HigherLowerRouteImport.update({
  id: '/higher-lower',
  path: '/higher-lower',
  getParentRoute: () => rootRouteImport,
} as any)
const HollywoodRoute = HollywoodRouteImport.update({
  id: '/hollywood',
  path: '/hollywood',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkOfFameRoute = WalkOfFameRouteImport.update({
  id: '/walk-of-fame',
  path: '/walk-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectImportRoute = ApiPublicConnectImportRouteImport.update({
  id: '/api/public/connect-import',
  path: '/api/public/connect-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyConnectPublishRoute =
  ApiPublicDailyConnectPublishRouteImport.update({
    id: '/api/public/daily-connect-publish',
    path: '/api/public/daily-connect-publish',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/higher-lower': typeof HigherLowerRoute
  '/hollywood': typeof HollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/walk-of-fame': typeof WalkOfFameRoute
  '/api/public/connect-import': typeof ApiPublicConnectImportRoute
  '/api/public/daily-connect-publish': typeof ApiPublicDailyConnectPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/higher-lower': typeof HigherLowerRoute
  '/hollywood': typeof HollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/walk-of-fame': typeof WalkOfFameRoute
  '/api/public/connect-import': typeof ApiPublicConnectImportRoute
  '/api/public/daily-connect-publish': typeof ApiPublicDailyConnectPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/higher-lower': typeof HigherLowerRoute
  '/hollywood': typeof HollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/walk-of-fame': typeof WalkOfFameRoute
  '/api/public/connect-import': typeof ApiPublicConnectImportRoute
  '/api/public/daily-connect-publish': typeof ApiPublicDailyConnectPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/higher-lower'
    | '/hollywood'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/walk-of-fame'
    | '/api/public/connect-import'
    | '/api/public/daily-connect-publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/higher-lower'
    | '/hollywood'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/walk-of-fame'
    | '/api/public/connect-import'
    | '/api/public/daily-connect-publish'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/higher-lower'
    | '/hollywood'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/walk-of-fame'
    | '/api/public/connect-import'
    | '/api/public/daily-connect-publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  HigherLowerRoute: typeof HigherLowerRoute
  HollywoodRoute: typeof HollywoodRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WalkOfFameRoute: typeof WalkOfFameRoute
  ApiPublicConnectImportRoute: typeof ApiPublicConnectImportRoute
  ApiPublicDailyConnectPublishRoute: typeof ApiPublicDailyConnectPublishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/higher-lower': {
      id: '/higher-lower'
      path: '/higher-lower'
      fullPath: '/higher-lower'
      preLoaderRoute: typeof HigherLowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hollywood': {
      id: '/hollywood'
      path: '/hollywood'
      fullPath: '/hollywood'
      preLoaderRoute: typeof HollywoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk-of-fame': {
      id: '/walk-of-fame'
      path: '/walk-of-fame'
      fullPath: '/walk-of-fame'
      preLoaderRoute: typeof WalkOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect-import': {
      id: '/api/public/connect-import'
      path: '/api/public/connect-import'
      fullPath: '/api/public/connect-import'
      preLoaderRoute: typeof ApiPublicConnectImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-connect-publish': {
      id: '/api/public/daily-connect-publish'
      path: '/api/public/daily-connect-publish'
      fullPath: '/api/public/daily-connect-publish'
      preLoaderRoute: typeof ApiPublicDailyConnectPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  HigherLowerRoute: HigherLowerRoute,
  HollywoodRoute: HollywoodRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WalkOfFameRoute: WalkOfFameRoute,
  ApiPublicConnectImportRoute: ApiPublicConnectImportRoute,
  ApiPublicDailyConnectPublishRoute: ApiPublicDailyConnectPublishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
