/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HigherLowerRouteImport } from './routes/higher-lower'
import { Route as HollywoodRouteImport } from './routes/hollywood'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalkOfFameRouteImport } from './routes/walk-of-fame'
import { Route as ConnectIndexRouteImport } from './routes/connect.index'
import { Route as ConnectDailyRouteImport } from './routes/connect.daily'
import { Route as DailyIndexRouteImport } from './routes/daily.index'
import { Route as DailyPersonRouteImport } from './routes/daily.person'
import { Route as DailyTimelineRouteImport } from './routes/daily.timeline'
import { Route as DailyTop10RouteImport } from './routes/daily.top-10'
import { Route as DailyUpDownRouteImport } from './routes/daily.up-down'
import { Route as ApiPublicConnectImportRouteImport } from './routes/api/public/connect-import'
import { Route as ApiPublicDailyConnectPublishRouteImport } from './routes/api/public/daily-connect-publish'
import { Route as ApiPublicDailyPublishRouteImport } from './routes/api/public/daily-publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HigherLowerRoute = HigherLowerRouteImport.update({
  id: '/higher-lower',
  path: '/higher-lower',
  getParentRoute: () => rootRouteImport,
} as any)
const HollywoodRoute = HollywoodRouteImport.update({
  id: '/hollywood',
  path: '/hollywood',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkOfFameRoute = WalkOfFameRouteImport.update({
  id: '/walk-of-fame',
  path: '/walk-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectIndexRoute = ConnectIndexRouteImport.update({
  id: '/connect/',
  path: '/connect/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectDailyRoute = ConnectDailyRouteImport.update({
  id: '/connect/daily',
  path: '/connect/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyIndexRoute = DailyIndexRouteImport.update({
  id: '/daily/',
  path: '/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPersonRoute = DailyPersonRouteImport.update({
  id: '/daily/person',
  path: '/daily/person',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyTimelineRoute = DailyTimelineRouteImport.update({
  id: '/daily/timeline',
  path: '/daily/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyTop10Route = DailyTop10RouteImport.update({
  id: '/daily/top-10',
  path: '/daily/top-10',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyUpDownRoute = DailyUpDownRouteImport.update({
  id: '/daily/up-down',
  path: '/daily/up-down',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectImportRoute = ApiPublicConnectImportRouteImport.update({
  id: '/api/public/connect-import',
  path: '/api/public/connect-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyConnectPublishRoute =
  ApiPublicDailyConnectPublishRouteImport.update({
    id: '/api/public/daily-connect-publish',
    path: '/api/public/daily-connect-publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDailyPublishRoute = ApiPublicDailyPublishRouteImport.update({
  id: '/api/public/daily-publish',
  path: '/api/public/daily-publish',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/higher-lower': typeof HigherLowerRoute
  '/hollywood': typeof HollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/walk-of-fame': typeof WalkOfFameRoute
  '/connect/daily': typeof ConnectDailyRoute
  '/daily/person': typeof DailyPersonRoute
  '/daily/timeline': typeof DailyTimelineRoute
  '/daily/top-10': typeof DailyTop10Route
  '/daily/up-down': typeof DailyUpDownRoute
  '/connect/': typeof ConnectIndexRoute
  '/daily/': typeof DailyIndexRoute
  '/api/public/connect-import': typeof ApiPublicConnectImportRoute
  '/api/public/daily-connect-publish': typeof ApiPublicDailyConnectPublishRoute
  '/api/public/daily-publish': typeof ApiPublicDailyPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/higher-lower': typeof HigherLowerRoute
  '/hollywood': typeof HollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/walk-of-fame': typeof WalkOfFameRoute
  '/connect/daily': typeof ConnectDailyRoute
  '/daily/person': typeof DailyPersonRoute
  '/daily/timeline': typeof DailyTimelineRoute
  '/daily/top-10': typeof DailyTop10Route
  '/daily/up-down': typeof DailyUpDownRoute
  '/connect': typeof ConnectIndexRoute
  '/daily': typeof DailyIndexRoute
  '/api/public/connect-import': typeof ApiPublicConnectImportRoute
  '/api/public/daily-connect-publish': typeof ApiPublicDailyConnectPublishRoute
  '/api/public/daily-publish': typeof ApiPublicDailyPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/higher-lower': typeof HigherLowerRoute
  '/hollywood': typeof HollywoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/walk-of-fame': typeof WalkOfFameRoute
  '/connect/daily': typeof ConnectDailyRoute
  '/daily/person': typeof DailyPersonRoute
  '/daily/timeline': typeof DailyTimelineRoute
  '/daily/top-10': typeof DailyTop10Route
  '/daily/up-down': typeof DailyUpDownRoute
  '/connect/': typeof ConnectIndexRoute
  '/daily/': typeof DailyIndexRoute
  '/api/public/connect-import': typeof ApiPublicConnectImportRoute
  '/api/public/daily-connect-publish': typeof ApiPublicDailyConnectPublishRoute
  '/api/public/daily-publish': typeof ApiPublicDailyPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/higher-lower'
    | '/hollywood'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/walk-of-fame'
    | '/connect/daily'
    | '/daily/person'
    | '/daily/timeline'
    | '/daily/top-10'
    | '/daily/up-down'
    | '/connect/'
    | '/daily/'
    | '/api/public/connect-import'
    | '/api/public/daily-connect-publish'
    | '/api/public/daily-publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/higher-lower'
    | '/hollywood'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/walk-of-fame'
    | '/connect/daily'
    | '/daily/person'
    | '/daily/timeline'
    | '/daily/top-10'
    | '/daily/up-down'
    | '/connect'
    | '/daily'
    | '/api/public/connect-import'
    | '/api/public/daily-connect-publish'
    | '/api/public/daily-publish'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/higher-lower'
    | '/hollywood'
    | '/privacy'
    | '/profile'
    | '/sitemap.xml'
    | '/terms'
    | '/walk-of-fame'
    | '/connect/daily'
    | '/daily/person'
    | '/daily/timeline'
    | '/daily/top-10'
    | '/daily/up-down'
    | '/connect/'
    | '/daily/'
    | '/api/public/connect-import'
    | '/api/public/daily-connect-publish'
    | '/api/public/daily-publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  HigherLowerRoute: typeof HigherLowerRoute
  HollywoodRoute: typeof HollywoodRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WalkOfFameRoute: typeof WalkOfFameRoute
  ConnectDailyRoute: typeof ConnectDailyRoute
  DailyPersonRoute: typeof DailyPersonRoute
  DailyTimelineRoute: typeof DailyTimelineRoute
  DailyTop10Route: typeof DailyTop10Route
  DailyUpDownRoute: typeof DailyUpDownRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
  DailyIndexRoute: typeof DailyIndexRoute
  ApiPublicConnectImportRoute: typeof ApiPublicConnectImportRoute
  ApiPublicDailyConnectPublishRoute: typeof ApiPublicDailyConnectPublishRoute
  ApiPublicDailyPublishRoute: typeof ApiPublicDailyPublishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/higher-lower': {
      id: '/higher-lower'
      path: '/higher-lower'
      fullPath: '/higher-lower'
      preLoaderRoute: typeof HigherLowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hollywood': {
      id: '/hollywood'
      path: '/hollywood'
      fullPath: '/hollywood'
      preLoaderRoute: typeof HollywoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk-of-fame': {
      id: '/walk-of-fame'
      path: '/walk-of-fame'
      fullPath: '/walk-of-fame'
      preLoaderRoute: typeof WalkOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/': {
      id: '/connect/'
      path: '/connect'
      fullPath: '/connect/'
      preLoaderRoute: typeof ConnectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/daily': {
      id: '/connect/daily'
      path: '/connect/daily'
      fullPath: '/connect/daily'
      preLoaderRoute: typeof ConnectDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/': {
      id: '/daily/'
      path: '/daily'
      fullPath: '/daily/'
      preLoaderRoute: typeof DailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/person': {
      id: '/daily/person'
      path: '/daily/person'
      fullPath: '/daily/person'
      preLoaderRoute: typeof DailyPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/timeline': {
      id: '/daily/timeline'
      path: '/daily/timeline'
      fullPath: '/daily/timeline'
      preLoaderRoute: typeof DailyTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/top-10': {
      id: '/daily/top-10'
      path: '/daily/top-10'
      fullPath: '/daily/top-10'
      preLoaderRoute: typeof DailyTop10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/up-down': {
      id: '/daily/up-down'
      path: '/daily/up-down'
      fullPath: '/daily/up-down'
      preLoaderRoute: typeof DailyUpDownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect-import': {
      id: '/api/public/connect-import'
      path: '/api/public/connect-import'
      fullPath: '/api/public/connect-import'
      preLoaderRoute: typeof ApiPublicConnectImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-connect-publish': {
      id: '/api/public/daily-connect-publish'
      path: '/api/public/daily-connect-publish'
      fullPath: '/api/public/daily-connect-publish'
      preLoaderRoute: typeof ApiPublicDailyConnectPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-publish': {
      id: '/api/public/daily-publish'
      path: '/api/public/daily-publish'
      fullPath: '/api/public/daily-publish'
      preLoaderRoute: typeof ApiPublicDailyPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  HigherLowerRoute: HigherLowerRoute,
  HollywoodRoute: HollywoodRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WalkOfFameRoute: WalkOfFameRoute,
  ConnectDailyRoute: ConnectDailyRoute,
  DailyPersonRoute: DailyPersonRoute,
  DailyTimelineRoute: DailyTimelineRoute,
  DailyTop10Route: DailyTop10Route,
  DailyUpDownRoute: DailyUpDownRoute,
  ConnectIndexRoute: ConnectIndexRoute,
  DailyIndexRoute: DailyIndexRoute,
  ApiPublicConnectImportRoute: ApiPublicConnectImportRoute,
  ApiPublicDailyConnectPublishRoute: ApiPublicDailyConnectPublishRoute,
  ApiPublicDailyPublishRoute: ApiPublicDailyPublishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
